language: node_js
node_js:
- node
- iojs
- '0.11'
- '0.12'
- iojs-v1.7
- iojs-v1.8
- iojs-v2.5
- iojs-v3.0
before_script:
- rm -rf ./coverage
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com" > .git/credentials
- npm run gulp preBuild
after_script:
- npm run gulp postBuild
- test -e ./coverage/lcov.info && < ./coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js
branches:
  only:
  - master
  - dev
cache:
  directories:
    - ./node_modules